<script>
    require(['jquery', 'domReady!'], function ($) {
        let carrierDiv = '#upsUserGuide_fifth-head';
        upsSmCurrentPlanNote($, '<?php echo $block->escapeHtml($block->upsSmallPlanNotice(), ['a', 'div']); ?>', carrierDiv);
    });
</script>
<div class="user_guide">
    <p>
        <?= $block->escapeHtml(__("The User Guide for this application is maintained on the publisher's website. To view it click <a href='%1' target='_blank'>here</a> or paste the following link into your browser.", $block->docUrl), ['a', 'div', 'target'])?>
    </p>
    <?= $block->escapeHtml($block->docUrl) ?>
</div>
